services:
  - type: web
    name: studysnap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 2 app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
